# Generated by Django 2.1.3 on 2018-11-26 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0, verbose_name='商品类别')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('subtitle', models.CharField(default='', max_length=200, verbose_name='商品子标题')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='商品主图')),
                ('sub_images', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='商品子图')),
                ('detail', models.TextField(default='', verbose_name='详细内容')),
                ('price', models.FloatField(default=0, verbose_name='商品价格')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('status', models.IntegerField(choices=[(1, '在售'), (2, '下架'), (3, '删除')], help_text='商品状态', verbose_name='商品状态')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品列表',
                'verbose_name_plural': '商品列表',
                'db_table': 'neuedu_product',
            },
        ),
        migrations.CreateModel(
            name='GoodsCarousel',
            fields=[
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
                'proxy': True,
                'indexes': [],
            },
            bases=('goods.goods',),
        ),
    ]
