# Generated by Django 2.0 on 2018-11-27 23:06

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=simditor.fields.RichTextField(verbose_name='详情内容'),
        ),
    ]
