# Generated by Django 2.0 on 2018-11-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '会员列表', 'verbose_name_plural': '会员列表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='answer',
            field=models.CharField(default='', max_length=100, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='question',
            field=models.CharField(default='', max_length=100, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
    ]
