# Generated by Django 2.0 on 2018-12-10 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('order_no', models.IntegerField(verbose_name='订单号')),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('product_name', models.CharField(default='', max_length=100, verbose_name='商品名称')),
                ('product_image', models.CharField(default='', max_length=500, verbose_name='商品图片')),
                ('current_unit_price', models.FloatField(verbose_name='实际金额')),
                ('quantity', models.IntegerField(verbose_name='商品数量')),
                ('total_price', models.IntegerField(verbose_name='商品总价')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'neuedu_order_item',
            },
        ),
    ]
