# Generated by Django 2.0 on 2018-11-27 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('order_no', models.IntegerField(verbose_name='订单号')),
                ('shipping_id', models.IntegerField(verbose_name='收货地址')),
                ('payment', models.FloatField(verbose_name='实际付款金额')),
                ('payment_type', models.IntegerField(choices=[(1, '在线支付')], help_text='付款方式', verbose_name='付款方式')),
                ('postage', models.IntegerField(default=0, verbose_name='运费')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (10, '未付款'), (20, '已付款'), (40, '已发货'), (50, '交易成功'), (60, '交易关闭')], help_text='订单状态', verbose_name='订单状态')),
                ('payment_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='付款时间')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发货时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='交易完成时间')),
                ('close_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='交易关闭时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
                'db_table': 'neuedu_order',
            },
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
            ],
            options={
                'verbose_name': '已取消订单',
                'verbose_name_plural': '已取消订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='FinishOrder',
            fields=[
            ],
            options={
                'verbose_name': '已完成订单',
                'verbose_name_plural': '已完成订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='NoPayOrder',
            fields=[
            ],
            options={
                'verbose_name': '未付款订单',
                'verbose_name_plural': '未付款订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
            ],
            options={
                'verbose_name': '已付款订单',
                'verbose_name_plural': '已付款订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='SendOrder',
            fields=[
            ],
            options={
                'verbose_name': '已发货订单',
                'verbose_name_plural': '已发货订单',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
    ]
